--customers by countries
SELECT
country,
COUNT (customer_key) AS Total_Customer 
FROM gold.dim_customers
Group by country
ORDER BY Total_Customer DESC;

--customers by gender
SELECT
gender,
COUNT (customer_key) AS Total_Customer 
FROM gold.dim_customers
Group by gender
ORDER BY Total_Customer DESC;

--products by category
SELECT
category,
COUNT (product_key) AS Total_product
FROM gold.dim_products
Group by category
ORDER BY Total_product DESC;

--average costs in each category
SELECT
category,
AVG (cost) AS avg_costs
FROM gold.dim_products
Group by category
ORDER BY avg_costs DESC

--total revenue generated for each category
SELECT 
p.category,
SUM (f.sales_amount) total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p 
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC; 

--total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

--distribution of sold items across countries
SELECT
    c.country,
    Sum(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;